### ISSUE TITLE
Place the "Add entry" section statically at the bottom of the browser window

### ISSUE THREAD

**Issue by aliquis** [icpc-live/autoanalyst#2]
The "Add entry" section is currently placed at the end of the page, which means that it might end up at the center of the browser window or below the bottom of the window, forcing the user to scroll back and forth. The user should instead always be able to access this section at the bottom of the browser window without scrolling.

**Comment by ghamerly** [comment]
Fixed in #5

**Comment by eldering** [comment]
Merged onto master.
