### ISSUE TITLE
Provide a way to tweet from another machine than domjudge-green

### ISSUE THREAD

**Issue by sjoqvist** [icpc-live/autoanalyst#27]
domjudge-green can't currently connect to the Twitter API as it doesn't have direct Internet access. To solve this, we could for example run a separate Katalyzer instance on a separate machine or write another program that parses the feed in order to generate tweets.

**Comment by eldering** [comment]
I'm pretty sure that the green network has (and should have) internet access. I can also `ping 8.8.8.8` from it.

**Comment by eldering** [comment]
I've configured Google's nameservers `8.8.8.8` and `8.8.4.4` on it, so now also `ping google.com` works. I think this should fix the Twitter connection issue.

**Comment by sjoqvist** [comment]
As @eldering says, it's working now.
