### ISSUE TITLE
Make selecting contest start time safer

### ISSUE THREAD

**Issue by sjoqvist** [icpc-live/autoanalyst#31]
Both `code_analyzer/analyzer.py` and `code_analyzer/githomes.py` use the query
```sql
SELECT start_time FROM contests ORDER BY start_time DESC LIMIT 1
```
to get the start time of the contest. I feel that
```sql
SELECT start_time FROM contests ORDER BY id DESC LIMIT 1
```
would be safer, since it would also handle advanced start times. Are there reasons to use the former?

**Comment by fredrikheintz** [comment]
I agree, please update.

Fredrik
