### ISSUE TITLE
Create a script for verifying the Twitter setup

### ISSUE THREAD

**Issue by sjoqvist** [icpc-live/autoanalyst#32]
It would be nice with a script that tests whether working Twitter credentials have been provided and whether Twitter support has been activated.

https://dev.twitter.com/rest/reference/get/account/verify_credentials

The script could possibly also do something with the `katalyzer.notifications.suppressUntil` config parameter, which is error-prone and easy to forget.

**Comment by stinny** [comment]
Similar to #33, I'd put that responsibility to Katalyzer, halting if the credentials are invalid. I'll look into it.
